name: orca
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas>=1.5.0
  - numpy>=1.21.0
  - scikit-learn>=1.0.0
  - tensorflow>=2.8.0
  - matplotlib>=3.5.0
  - pip
  - pip:
    - ta>=0.10.0
    - python-dotenv>=0.19.0
    - ccxt>=2.0.0
    - binance-futures-connector>=3.0.0 